import Card from '../common/Card'
import ProgressBar from '../common/ProgressBar'

export default function CoachContextPanel({ readiness, topFocus, version, completion }) {
  return (
    <Card className="hidden lg:block">
      <p className="text-xs text-slate-500 mb-3">What your coach can see</p>
      <div className="space-y-3">
        <ProgressBar label="Plan completion" value={completion} />
        <ProgressBar label="Overall readiness" value={readiness.overall} />
        <ProgressBar label="DSA" value={readiness.dsa} />
        <ProgressBar label="System Design" value={readiness.systemDesign} tone="amber" />
      </div>
      <div className="mt-4 pt-4 border-t border-slate-100">
        <p className="text-xs text-slate-500 mb-1">Currently focused on</p>
        <p className="text-sm font-medium text-ink">{topFocus}</p>
      </div>
      <p className="mt-4 text-xs text-slate-400">
        Answers are generated by Gemini from your goal, Plan v{version} and your task progress.
      </p>
    </Card>
  )
}
