const express = require('express')
const cors = require('cors')

const healthRoutes = require('./routes/healthRoutes')
const authRoutes = require('./routes/authRoutes')
const clientDate = require('./middleware/clientDate')
const userRoutes = require('./routes/userRoutes')
const goalRoutes = require('./routes/goalRoutes')
const planRoutes = require('./routes/planRoutes')
const notFound = require('./middleware/notFound')
const errorHandler = require('./middleware/errorHandler')
const progressRoutes = require('./routes/progressRoutes')
const recoveryRoutes = require('./routes/recoveryRoutes')
const aiRoutes = require('./routes/aiRoutes')
const recommendationRoutes = require('./routes/recommendationRoutes')
const weakAreaRoutes = require('./routes/weakAreaRoutes')
const insightRoutes = require('./routes/insightRoutes')
const coachRoutes = require('./routes/coachRoutes')
const mockInterviewRoutes = require('./routes/mockInterviewRoutes')
const app = express()
const metricsMiddleware = require('./middleware/metrics')
const { register } = require('./config/metrics')
app.use(cors())
app.use(express.json({ limit: '1mb' }))
app.use(clientDate)
app.use(metricsMiddleware)
app.use('/api', healthRoutes)
app.use('/api/auth', authRoutes)
app.use('/api/users', userRoutes)
app.use('/api/goals', goalRoutes)
app.use('/api/plans', planRoutes)
app.use('/api/progress', progressRoutes)
app.use('/api/recovery', recoveryRoutes)
app.use('/api/ai', aiRoutes)
app.use('/api/recommendations', recommendationRoutes)
app.use('/api/weak-areas', weakAreaRoutes)
app.use('/api/insights', insightRoutes)
app.use('/api/coach', coachRoutes)
app.use(
  '/api/mock-interview',
  mockInterviewRoutes
)
app.get('/metrics', async (req, res) => {
  res.set('Content-Type', register.contentType)
  res.end(await register.metrics())
})
app.use(notFound)
app.use(errorHandler)

module.exports = app
